config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'quizzes#index'

  resources :themes, only: %i(new create index)

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/theme.rb
class Theme < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, length: { in: 1..15 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: %i(username))
    end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  def index
    
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController

  def index
    @themes = Theme.all.order('created_at DESC')
  end

  def new
    @theme = Theme.new
  end

  def create
    @theme = Theme.new(theme_params)
    if @theme.save
      redirect_to root_path
      flash[:notice] = "お題を作成しました。"
    else
      redirect_to root_path
      flash[:alert] = "お題の作成に失敗しました。"
    end
  end

  private
  def theme_params
    params.require(:theme).permit(:word, :choice1, :choice2, :choice3, :choice4, :choice5, :choice6, :choice7, :choice8)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pretender</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="body">

    <%# navbarはpartial/navbar.html.erbの中 %>
    <%= render 'partial/navbar' %>

    <%# flashメッセージを表示 %>
    <% if flash[:notice] %>
      <div class="alert alert-info">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/partial/_navbar.html.erb
    <%# navbar %>
    <nav class="global-nav">
      <div class="container">
        <div class="navigation">
          <ul class="left-actions">
            <li class="nav-item">
              <%= link_to "PRETENDER", root_path, class: "nav-link" %>
            </li>
          </ul>

          <ul class="right-actions">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "問題を作成する", "#", class: "btn btn-primary quiz-btn" %>
            </li>
            <li class="nav-item">
              <%= link_to "お題を作成する", new_theme_path, class: "btn btn-primary theme-btn" %>
            </li>
            <li class="nav-item">
              <%= link_to "お題一覧を見る", themes_path, class: "btn btn-primary theme-btn" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "logout" %>
            </li>

            <% else %>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: "btn btn-primary signup-btn" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", user_session_path, class: "login" %>
            </li>
          <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <%# end of navbar %>

app/views/quizzes/index.html.erb
<div class="wrapper">
  <h1>ログイン後のメインページ予定</h1>
  <%= link_to "仮のボタンです", "#", class: "btn btn-info" %>
</div>

app/views/themes/index.html.erb
<div class="theme-card card">
  <div class="card-header">
    お題一覧
  </div>
  <% @themes.each do |theme| %>
    <div class="card">
      <div class="stream-item">
        <div class="content">
          <div class="stream-item-header">
            <div class="main-content">
              <h2 class="word"><%= theme.word %></h2>
              <ul class="choices">
                <li><span class="choice">Ａ</span><%= theme.choice1 %></li>
                <li><span class="choice">Ｂ</span><%= theme.choice2 %></li>
                <li><span class="choice">Ｃ</span><%= theme.choice3 %></li>
                <li><span class="choice">Ｄ</span><%= theme.choice4 %></li>
                <li><span class="choice">Ｅ</span><%= theme.choice5 %></li>
                <li><span class="choice">Ｆ</span><%= theme.choice6 %></li>
                <li><span class="choice">Ｇ</span><%= theme.choice7 %></li>
                <li><span class="choice">Ｈ</span><%= theme.choice8 %></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/themes/new.html.erb
<div class="card theme-card">
  <div class="card-header">
    お題を作成する
  </div>
  <div class="card-body">
    <%= form_with model: @theme do |f| %>
      <div class="theme-body">
        <%= f.text_field :word, placeholder: "お題は？", class: "form-control" %>
        <%= f.text_field :choice1, placeholder: "１つの目の選択肢", class: "form-control" %>
        <%= f.text_field :choice2, placeholder: "２つの目の選択肢", class: "form-control" %>
        <%= f.text_field :choice3, placeholder: "３つの目の選択肢", class: "form-control" %>
        <%= f.text_field :choice4, placeholder: "４つの目の選択肢", class: "form-control" %>
        <%= f.text_field :choice5, placeholder: "５つの目の選択肢", class: "form-control" %>
        <%= f.text_field :choice6, placeholder: "６つの目の選択肢", class: "form-control" %>
        <%= f.text_field :choice7, placeholder: "７つの目の選択肢", class: "form-control" %>
        <%= f.text_field :choice8, placeholder: "８つの目の選択肢", class: "form-control" %>
      </div>
      <div class="buttons">
        <%= f.submit "作成", class: "btn btn-primary theme-btn" %>
      </div>
    <% end %>
  </div>
</div>